spring.application.name=demo

# H2 in-memory DB
spring.datasource.url=jdbc:h2:mem: testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 console - vào http://Localhost:8080/h2-console khi app chay
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA - hiên SQL ra console (debug r?t quan trong!)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# T?o l?i schema m?i L?n ch?y (ch? dùng cho dev!)
spring.jpa.hibernate.ddl-auto=create-drop